module.exports = {
    nodeEnv:                            process.env.NODE_ENV,
    appPort:                            process.env.PORT,
    apiKey:                             process.env.EXHIBITS_API_KEY,
    elasticDomain:                      process.env.ELASTIC_DOMAIN,
    elasticIndex:                       process.env.ELASTIC_INDEX,
    repositoryDomain:                   process.env.REPOSITORY_DOMAIN,
    repositoryApiKey:                   process.env.REPOSITORY_API_KEY,
    repositoryItemResourceEndpoint:     process.env.REPOSITORY_ITEM_RESOURCE_ENDPOINT,
    repositoryItemThumbnailEndpoint:    process.env.REPOSITORY_ITEM_THUMBNAIL_ENDPOINT,
    repositoryItemDataEndpoint:         process.env.REPOSITORY_ITEM_DATA_ENDPOINT,
    repositorySearchEndpoint:           process.env.REPOSITORY_SEARCH_ENDPOINT,
    repositoryObjectPageUrl:            process.env.REPOSITORY_OBJECT_PAGE_URL,
    repositoryCollectionPageUrl:        process.env.REPOSITORY_COLLECTION_PAGE_URL,
    repositoryIIIFServiceUrl:           process.env.REPOSITORY_IIIF_SERVICE_URL,
    repositoryIIIFImageUrl:             process.env.REPOSITORY_IIIF_IMAGE_URL,
    repositoryIIIFManifestUrl:          process.env.REPOSITORY_IIIF_MANIFEST_URL,
    repositoryIIIFThumbnailUrl:         process.env.REPOSITORY_IIIF_THUMBNAIL_URL,
    resourceLocalStorageLocation:       process.env.RESOURCE_LOCATION,
    archivalMetadataProviderDomain:     process.env.ARCHIVAL_METADATA_PROVIDER_DOMAIN,
}